apiVersion: v1
kind: Secret
metadata:
  name: clickbus-secrets
  namespace: clickbus
type: Opaque
stringData:
  # Replace with your actual Azure Service Bus connection string
  # AZURE_SERVICE_BUS_CONNECTION_STRING: "Endpoint=sb://xxx.xxx.windows.net/;SharedAccessKeyName=xxx;SharedAccessKey=xxx"
  
  # Note: Use stringData instead of data to avoid base64 encoding
  # Kubernetes will automatically base64 encode these values
